name: "Leap Query Lookup"
author: RapidCircle
description: "Get Lookup Value"
inputs:
  TenantId:
    description: "TenantId"
    required: true
  ClientId:
    description: "ClientId"
    required: true
  ClientSecret:
    description: "ClientSecret"
    required: true
  LookupServiceIdentifier:
    description: "Lookup Service Identifier"
    required: true
  TableName:
    description: "Name of the lookup table"
    required: true
  Query:
    description: "Lookup table query"
    required: true
    default: ""
outputs:
  LookupTableValueJSON:
    description: "Lookup Value"
    value: ${{ steps.fetch-lookup-value.outputs.LookupValue }}
runs:
  using: "composite"
  steps:
    - name: Query Lookup Table
      id: fetch-lookup-value
      shell: pwsh
      env:
        LookupResourceId: 6046ae5b-af14-4f76-9c06-cda61515880a
        HostURL: "https://staging-dna-lkup-api.azurewebsites.net"
      run: ${{ github.action_path }}/script/Query-LookupTable.ps1 `
        -TableName ${{ inputs.TableName }} `
        -Query ${{ inputs.Query }} `
        -TenantId ${{ inputs.TenantId }} `
        -ClientId ${{ inputs.ClientId }} `
        -ClientSecret ${{ inputs.ClientSecret }} `
        -LookupServiceIdentifier ${{ inputs.LookupServiceIdentifier }}
