name: "Leap Query Lookup"
author: RapidCircle
description: "Get Desired Lookup Value"
inputs:
  TenantId:
    description: "TenantId"
    required: true
  ClientId:
    description: "ClientId"
    required: true
  ClientSecret:
    description: "ClientSecret"
    required: true
  LookupServiceIdentifier:
    description: "Lookup Service Identifier"
    required: true
  HostURL:
    description: "HostURL"
    required: true
  TableName:
    description: "Name of the lookup table"
    required: true
  Query:
    description: "Lookup table query"
    required: false
    default: ""
  FirstOrDefault:
    description: "If this flag is set to false, get all items that meet query from Lookup table"
    required: false
outputs:
  LookupTableValueJSON:
    description: "Lookup Value"
    value: ${{ steps.fetch-lookup-value.outputs.LookupValue }}
runs:
  using: "composite"
  steps:
    - name: validate-inputs
      shell: bash
      run: |
        [[ "${{ inputs.TableName }}" ]] || { echo "TableName input is required" ; exit 1; }
    - name: Query Lookup Table
      id: fetch-lookup-value
      shell: pwsh
      env:
        HostURL: ${{ inputs.HostURL }}
        TableName: ${{ inputs.TableName }}
        Query: ${{ inputs.Query }}
        TenantId: ${{ inputs.TenantId }}
        ClientId: ${{ inputs.ClientId }}
        ClientSecret: ${{ inputs.ClientSecret }}
        LookupServiceIdentifier: ${{ inputs.LookupServiceIdentifier }}
        FirstOrDefault: ${{ inputs.FirstOrDefault }}
      run: ${{ github.action_path }}/script/Query-LookupTable.ps1
