name: "Leap Query Lookup"
author: RapidCircle
description: "Get Lookup Value"
inputs:
  TenantId:
    description: "TenantId"
    required: true
  ClientId:
    description: "ClientId"
    required: true
  ClientSecret:
    description: "ClientSecret"
    required: true
  ServiceIdentifier:
    description: "Lookup Service Identifier"
    required: true
  TableName:
    description: "Name of the lookup table"
    required: true
  Query:
    description: "Lookup table query"
    required: false
  Column:
    description: "Name of the column"
    required: false
outputs:
  LookupTableValueJSON:
    description: "Lookup Value"
    value: ${{ steps.fetch-lookup-value.outputs.LookupValue }}
runs:
  using: "composite"
  steps:
    - name: Check out action repo
      uses: actions/checkout@dev
      with:
        repository: RapidCircle/leap-lookup-query
    - name: Query Lookup Table
      id: fetch-lookup-value
      shell: pwsh
      env:
        LookupResourceId: 6046ae5b-af14-4f76-9c06-cda61515880a
      run: ${{ github.action_path }}/script/Get-LookupTableOutput.ps1 `
        -TableName ${{ inputs.TableName }} `
        -Query ${{ inputs.Query }} `
        -Column ${{ inputs.Column }} `
        -TenantId ${{ inputs.TenantId }} `
        -ClientId ${{ inputs.ClientId }} `
        -ClientSecret ${{ inputs.ClientSecret }}
        -ServiceIdentifier ${{ inputs.ServiceIdentifier }}
